// Traduction des libellés de garanties Brio (néerlandais) vers le français.
// Les garanties composées sont séparées par « / » : on traduit chaque terme atomique.
const MAP = {
  'BA Motorvoertuig': 'RC véhicule automoteur',
  'Eigen Schade': 'Dégâts propres (Omnium)',
  'Rechtsbijstand': 'Protection juridique',
  'Glasbraak (Voertuig)': 'Bris de vitres (Véhicule)',
  'Waterschade': 'Dégâts des eaux',
  'Bijstand': 'Assistance',
  'Rechtsbijstand (Voertuig)': 'Protection juridique (Véhicule)',
  'Brand alleen': 'Incendie seul',
  'Storm, Hagel en Sneeuwdruk': 'Tempête, grêle et pression de la neige',
  'BA gezin (KB + waarborguitbreidingen)': 'RC familiale (AR + extensions de garantie)',
  'Natuurkrachten (Voertuig)': 'Forces de la nature (Véhicule)',
  'Brand Algemeen': 'Incendie général',
  'Glasbraak': 'Bris de vitres',
  'Repatriëring': 'Rapatriement',
  'Natuurrampen (specifiek)': 'Catastrophes naturelles (spécifique)',
  'Diefstal': 'Vol',
  'Aanrijding met wild (Voertuig)': 'Collision avec gibier (Véhicule)',
  'BA Uitbating': 'RC exploitation',
  'Elektriciteit': 'Électricité',
  'Niet-individueel genoemde waarborgen': 'Garanties non nommées individuellement',
  'Rechtsbijstand bewoning': 'Protection juridique habitation',
  'Rechtsbijstand privé leven': 'Protection juridique vie privée',
  'Overstroming': 'Inondation',
  'Indirecte Verliezen': 'Pertes indirectes',
  'Diefstal (Voertuig)': 'Vol (Véhicule)',
  'Volledige Omnium': 'Omnium complète',
  'BA Bezittingen': 'RC biens',
  'Ziekenhuisopname': 'Hospitalisation',
  'Arbeidsongevallen': 'Accidents du travail',
  'BA Na Levering': 'RC après livraison',
  'BA Gezin (KB)': 'RC familiale (AR)',
  'Aanvullende waarborgen': 'Garanties complémentaires',
  'Aanvullende waarborgen (BER)': 'Garanties complémentaires (BER)',
  'Bestuurder': 'Conducteur',
  'Pre- en post- hospitalisatiekosten': 'Frais pré- et post-hospitalisation',
  'Inzittenden': 'Occupants',
  'Medische Kosten': 'Frais médicaux',
  'BA Toevertrouwde voorwerpen': 'RC objets confiés',
  'Gedeeltelijke Omnium': 'Omnium partielle',
  'BA Algemeen': 'RC générale',
  'AVRI premie': 'AVRI prime',
  'AVRI rente': 'AVRI rente',
  'Tijdelijke invaliditeit': 'Invalidité temporaire',
  'Aanraking voertuigen': 'Contact entre véhicules',
  'Gewaarborgd inkomen': 'Revenu garanti',
  'BA Beroep': 'RC professionnelle',
  'Natuurrampen (Tarificatiebureau)': 'Catastrophes naturelles (Bureau de tarification)',
  'Bestendige invaliditeit': 'Invalidité permanente',
  'Aardbeving': 'Tremblement de terre',
  'Rechtsbijstand beroep': 'Protection juridique professionnelle',
  'Brand (Voertuig)': 'Incendie (Véhicule)',
  'Rechtsbijstand verkeer': 'Protection juridique circulation',
  'Rechtsbijstand (KB)': 'Protection juridique (AR)',
  'Ongevallen privé leven': 'Accidents vie privée',
  'Ongevallen privéleven': 'Accidents vie privée',
  'Tandbehandelingskosten': 'Frais de soins dentaires',
  'BA Materiële schade': 'RC dégâts matériels',
  'Geldelijke verliezen': 'Pertes pécuniaires',
  'Elektriciteit& Electronica': 'Électricité & électronique',
  'Annulering': 'Annulation',
  'Technische Verzekeringen': 'Assurances techniques',
  'Inbraakschade': 'Dégâts par effraction',
  'Overlijden': 'Décès',
  "Alle Risico's": 'Tous risques',
  'Vervoerde goederen': 'Marchandises transportées',
  'Beschadiging onroerende': 'Dégâts aux biens immobiliers',
  "Alle Bouwwerf Risico's": 'Tous risques chantier',
  'Weg Van en Naar het Werk': 'Trajet domicile-travail',
  'AVRO': 'AVRO',
  'Rookschade': 'Dégâts de fumée',
  'Reisgoed': 'Bagages',
  'Behandelingskosten van zware ziekten': 'Frais de traitement maladies graves',
  'Leven': 'Vie',
  'BA Lichamelijke schade': 'RC dégâts corporels',
  'Sanering': 'Assainissement',
  'Insolventie van derden': 'Insolvabilité de tiers',
}

export function traduitGarantie(val) {
  if (!val) return val
  return String(val)
    .split(' / ')
    .map(t => { const k = t.trim(); return MAP[k] || k })
    .filter(Boolean)
    .join(' / ')
}

export default traduitGarantie
